version: '3'
services:
  nextcloud-app:
    container_name: nextcloud-app
    image: nextcloud:fpm
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - nextcloud_app_data:/var/www/html:rw
      - ./nextcloud_config:/var/www/html/config:rw
    environment:
      - SERVICE_HOST=$SERVICE_HOST
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
      - REDIS_HOST=nextcloud_redis
      - REDIS_HOST_PORT=6379
      - SMTP_HOST=$SMTP_HOST
      - SMTP_SECURE=$SMTP_SECURE
      - SMTP_PORT=$SMTP_PORT
      - SMTP_AUTHTYPE=$SMTP_AUTHTYPE
      - SMTP_NAME=$SMTP_NAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
      - MAIL_DOMAIN=$MAIL_DOMAIN

  nextcloud_db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD

  nextcloud_redis:
    image: redis:latest
    container_name: nextcloud_redis
    restart: always

  nextcloud_cron:
    image: nextcloud:fpm
    container_name: nextcloud_cron
    restart: always
    depends_on:
      - nextcloud_db
      - nextcloud_redis
      - nextcloud-app
    volumes:
      - nextcloud_app_data:/var/www/html:rw
      - ./nextcloud_config:/var/www/html/config:rw
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
      - REDIS_HOST=nextcloud_redis
      - REDIS_HOST_PORT=6379
    entrypoint: /cron.sh

  onlyoffice-app:
    container_name: onlyoffice-app
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_ENABLED=false
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    depends_on:
      - nextcloud-app
      - onlyoffice-app
      - certbot
    ports:
      - 80:80
      - 443:443
    expose:
      - '8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_app_data:/var/www/html
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  document_data:
  document_log:
  nextcloud_app_data:
  nextcloud-db:
